### ISSUE TITLE
Generalization based on party instead of current leadership

### ISSUE THREAD

**Issue by ayushman264** [SJSUFall2019-CMPE272/WhomToVote-#1]
Political Leadership mostly changes after every election. How can the statistics of a government under previous leaders suggest that the country will progress under any future leader of the same party? Generalizing growth with only economic and literacy growth figures of a political party does not help voter decide whether the leader contesting election this time will live up to the expectation. ( Example : Indian National Congress under Mrs.Indira Gandhi's leadership was very much different from what it is under Mr. Rahul Gandhi's current leadership). How will you resolve this anomaly?

**Comment by ashtalele70** [comment]
We are analyzing the data in a year for only two parties and based on that we are predicting the expected winner in the upcoming elections. In a span of a year, the leaders are almost the same. Taking this factor into consideration only, we trained our model with the data of a year and not many years.
