### ISSUE TITLE
Similar data already available / Value of the system?

### ISSUE THREAD

**Issue by chets619** [SJSUFall2019-CMPE272/WhomToVote-#2]
The analyzed data of economic growth and literacy rate of India is uploaded on all major platforms like "World Bank" and "Niti Ayog" which is publicly accessible and graphically demonstrated on many websites, what value will your system add to this analysis? (https://data.worldbank.org/country/india) (https://niti.gov.in/content/national-statistics)

**Comment by ashtalele70** [comment]
Firstly, the website "World Bank" is used for granting loans and the website "Niti Ayog" works as a policy think tank of the Government of India. 
Our main focus is voting prediction and voting data analysis which is not done by any of these.
