### ISSUE TITLE
Technical Issue

### ISSUE THREAD

**Issue by agrawalnaman** [SJSUFall2019-CMPE272/WhomToVote-#4]
How will you prove to the world that you are unbiased in processing information and giving predictions and that you are not influenced by any particular political group ideology? The processing should be whitebox and should be done using public ledgers such that it is transparent to anybody who would like to use it. Will you be using blockchain for public ledgers?

**Comment by ashtalele70** [comment]
We are using the past data to train our model, which states that we are using the facts and not our own experience or thinking. So, our prediction is unbiased. We are not using blockchain.
