### ISSUE TITLE
Lack of datapoints

### ISSUE THREAD

**Issue by ahuja101992** [SJSUFall2019-CMPE272/WhomToVote-#5]
Only three data points have been mentioned, they majorly focus on the economic growth of the country. But there are various other factors such as Happiness Index of the population, political agenda and future vision of the leaders which have to be taken into account before suggesting any meaningful advisory. Some nations are economically progressing but have a dictatorship regime which is unacceptable to any democratic republic (Example: Iraq under Saddam Hussein was rich oil trading economy but the dictatorial governance left country poor and undeveloped in the end.) How do you plan to incorporate other factors into the system?

**Comment by ashtalele70** [comment]
We have taken four major factors which are the main indicators of the health of a democracy.
1. Median Age
2. Unemployment Rate
3. Education
4. Per Capita Income
